name: student_records
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: tnc1997 <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mongo_dart: ^0.3.0

dev_dependencies:
  test: ^1.0.0
